compressionLevel: mixed

enableGlobalCache: false

packageExtensions:
  "@urql/devtools@*":
    dependencies:
      "@urql/core": "*"
  eslint-module-utils@*:
    dependencies:
      "@typescript-eslint/parser": "*"
  eslint-plugin-import-x@*:
    dependencies:
      "@typescript-eslint/parser": "*"
  react-leaflet-cluster@*:
    dependencies:
      "@react-leaflet/core": "*"
  swiper@*:
    dependencies:
      react: "*"

supportedArchitectures:
  cpu:
    - arm64
    - x64
  libc:
    - glibc
    - musl
  os:
    - darwin
    - linux

yarnPath: .yarn/releases/yarn-4.5.1.cjs
