import {
  BusinessCenterTwoTone,
  DescriptionTwoTone,
  DomainTwoTone,
  EnergySavingsLeafTwoTone,
  EuroTwoTone,
  HandymanTwoTone,
  PeopleAltTwoTone,
  SettingsTwoTone,
  VpnKeyTwoTone,
} from '@mui/icons-material';
import { MenuGroup } from '@realgimm5/frontend-common/interfaces';

import { RawFeature } from '../enums/RawFeature';

export const menuConfig: MenuGroup[] = [
  {
    children: [
      {
        title: 'core.menu.registry.title',
        icon: PeopleAltTwoTone,
        type: 'group',
        features: [RawFeature.ANAG_SUBJECT_BASE, RawFeature.ANAG_SUBJECT_ORGUNIT],
        children: [
          {
            title: 'core.menu.registry.subjects',
            url: '/app/registry/subjects',
            type: 'link',
            feature: RawFeature.ANAG_SUBJECT_BASE,
          },
          {
            title: 'core.menu.registry.org_units',
            url: '/app/registry/organizational-units',
            type: 'link',
            feature: RawFeature.ANAG_SUBJECT_ORGUNIT,
          },
        ],
      },
      {
        title: 'core.menu.real_estate.title',
        icon: DomainTwoTone,
        type: 'group',
        features: [
          RawFeature.ASST_ESTATE_BASE,
          RawFeature.ASST_ESTATEUNIT_BASE,
          RawFeature.ASST_CADASTRALUNIT_BASE,
          RawFeature.ASST_ESTATE_CATALOGUE,
        ],
        children: [
          {
            title: 'core.menu.real_estate.estates',
            url: '/app/real-estate/estates',
            type: 'link',
            feature: RawFeature.ASST_ESTATE_BASE,
          },
          {
            title: 'core.menu.real_estate.estate_units',
            url: '/app/real-estate/estate-units',
            type: 'link',
            feature: RawFeature.ASST_ESTATEUNIT_BASE,
          },
          {
            title: 'core.menu.real_estate.cadastral_units',
            url: '/app/real-estate/cadastral-units',
            type: 'link',
            feature: RawFeature.ASST_CADASTRALUNIT_BASE,
          },
          {
            title: 'core.menu.real_estate.catalogues',
            url: '/app/real-estate/catalogues',
            type: 'link',
            feature: RawFeature.ASST_ESTATE_CATALOGUE,
          },
        ],
      },
      {
        title: 'core.menu.asset_management.title',
        icon: BusinessCenterTwoTone,
        type: 'group',
        features: [
          RawFeature.PROP_CONTRACT_BASE,
          RawFeature.PROP_BILL_BASE,
          RawFeature.PROP_ADMINISTRATION_BASE,
          RawFeature.PROP_REGISTRY_COMMUNICATION,
          RawFeature.PROP_REGISTRATION_PAYMENT,
        ],
        children: [
          {
            title: 'core.menu.asset_management.active_contracts',
            url: '/app/asset-management/contracts/active',
            type: 'link',
            feature: RawFeature.PROP_CONTRACT_BASE,
          },
          {
            title: 'core.menu.asset_management.passive_contracts',
            url: '/app/asset-management/contracts/passive',
            type: 'link',
            feature: RawFeature.PROP_CONTRACT_BASE,
          },
          {
            title: 'core.menu.asset_management.active_bills',
            url: '/app/asset-management/bills/active',
            type: 'link',
            feature: RawFeature.PROP_BILL_BASE,
          },
          {
            title: 'core.menu.asset_management.passive_bills',
            url: '/app/asset-management/bills/passive',
            type: 'link',
            feature: RawFeature.PROP_BILL_BASE,
          },
          {
            title: 'core.menu.asset_management.administration',
            url: '/app/asset-management/administrations',
            type: 'link',
            feature: RawFeature.PROP_ADMINISTRATION_BASE,
          },
          {
            title: 'core.menu.asset_management.registry_communications',
            url: '/app/asset-management/registry-communications',
            type: 'link',
            feature: RawFeature.PROP_REGISTRY_COMMUNICATION,
          },
          {
            title: 'core.menu.asset_management.registration_payments',
            url: '/app/asset-management/registration-payments',
            type: 'link',
            feature: RawFeature.PROP_REGISTRATION_PAYMENT,
          },
        ],
      },
      {
        title: 'core.menu.tax_management.title',
        icon: EuroTwoTone,
        type: 'group',
        features: [RawFeature.ASST_ASSET_TAX_BASE, RawFeature.COMMON_REPORT_GENERATORS],
        children: [
          {
            title: 'core.menu.tax_management.asset_taxes',
            url: '/app/tax-management/asset-taxes',
            type: 'link',
            feature: RawFeature.ASST_ASSET_TAX_BASE,
          },
          {
            title: 'core.menu.tax_management.report_generator',
            url: '/app/tax-management/report',
            type: 'link',
            feature: RawFeature.COMMON_REPORT_GENERATORS,
          },
        ],
      },
      {
        title: 'core.menu.energy_management.title',
        icon: EnergySavingsLeafTwoTone,
        type: 'group',
        features: [RawFeature.NRGY_SERVICE_BASE, RawFeature.NRGY_COSTCHARGE_BASE],
        children: [
          {
            title: 'core.menu.energy_management.utility_services',
            url: '/app/energy-management/utility-services',
            type: 'link',
            feature: RawFeature.NRGY_SERVICE_BASE,
          },
          {
            title: 'core.menu.energy_management.cost_charges',
            url: '/app/energy-management/cost-charges',
            type: 'link',
            feature: RawFeature.NRGY_COSTCHARGE_BASE,
          },
          {
            title: 'core.menu.energy_management.cost_charge_analysis',
            url: '/app/energy-management/cost-charge-analysis',
            type: 'link',
            feature: RawFeature.NRGY_COSTCHARGE_BASE,
          },
        ],
      },
      {
        title: 'core.menu.maintenance.title',
        icon: HandymanTwoTone,
        type: 'group',
        url: '/app/maintenance',
        features: [
          RawFeature.FCLT_CONTRACT_BASE,
          RawFeature.FCLT_CONFIG,
          RawFeature.FCLT_PRICE_LIST_BASE,
          RawFeature.FCLT_PRICE_LIST_ARTICLES,
          RawFeature.FCLT_TICKET,
        ],
        children: [
          {
            title: 'core.menu.maintenance.tickets',
            url: '/app/maintenance/tickets',
            type: 'link',
            feature: RawFeature.FCLT_TICKET,
          },
          {
            title: 'core.menu.maintenance.tickets_calendar',
            url: '/app/maintenance/tickets-calendar',
            type: 'link',
            feature: RawFeature.FCLT_TICKET,
          },
          {
            title: 'core.menu.maintenance.tickets_timetable.title',
            type: 'group',
            features: [RawFeature.FCLT_TICKET],
            children: [
              {
                title: 'core.menu.maintenance.tickets_timetable.expired',
                url: '/app/maintenance/tickets-timetable/expired',
                type: 'link',
                feature: RawFeature.FCLT_TICKET,
              },
              {
                title: 'core.menu.maintenance.tickets_timetable.expiring',
                url: '/app/maintenance/tickets-timetable/expiring',
                type: 'link',
                feature: RawFeature.FCLT_TICKET,
              },
            ],
          },
          {
            title: 'core.menu.maintenance.facility_contracts',
            url: '/app/maintenance/facility-contracts',
            type: 'link',
            feature: RawFeature.FCLT_CONTRACT_BASE,
          },
          {
            title: 'core.menu.maintenance.work_teams',
            url: '/app/maintenance/work-teams',
            type: 'link',
            feature: RawFeature.FCLT_CONFIG,
          },
          {
            title: 'core.menu.maintenance.price_lists',
            url: '/app/maintenance/price-lists',
            type: 'link',
            feature: RawFeature.FCLT_PRICE_LIST_BASE,
          },
          {
            title: 'core.menu.maintenance.price_list_articles',
            url: '/app/maintenance/price-list-articles',
            type: 'link',
            feature: RawFeature.FCLT_PRICE_LIST_ARTICLES,
          },
        ],
      },
      {
        title: 'core.menu.repository.title',
        icon: DescriptionTwoTone,
        type: 'group',
        features: [RawFeature.DOCUMENTS_BASE],
        children: [
          {
            title: 'core.menu.repository.documents',
            url: '/app/repository/documents',
            match: 'complete',
            type: 'link',
            feature: RawFeature.DOCUMENTS_BASE,
          },
          {
            title: 'core.menu.repository.expired_documents',
            url: '/app/repository/documents/expired',
            match: 'complete',
            type: 'link',
            feature: RawFeature.DOCUMENTS_BASE,
          },
          {
            title: 'core.menu.repository.expiring_documents',
            url: '/app/repository/documents/expiring',
            match: 'complete',
            type: 'link',
            feature: RawFeature.DOCUMENTS_BASE,
          },
        ],
      },
      {
        title: 'core.menu.system.title',
        icon: VpnKeyTwoTone,
        type: 'group',
        features: [RawFeature.ADMIN_USERS_AND_GROUPS, RawFeature.ADMIN_AUDIT_LOG, RawFeature.ADMIN_CONFIG],
        children: [
          {
            title: 'core.menu.system.groups',
            url: '/app/system/groups',
            type: 'link',
            feature: RawFeature.ADMIN_USERS_AND_GROUPS,
          },
          {
            title: 'core.menu.system.users',
            url: '/app/system/users',
            type: 'link',
            feature: RawFeature.ADMIN_USERS_AND_GROUPS,
          },
          {
            title: 'core.menu.system.audit_events',
            url: '/app/system/audit-events',
            type: 'link',
            feature: RawFeature.ADMIN_AUDIT_LOG,
          },
          {
            title: 'core.menu.system.configs',
            url: '/app/system/configs',
            type: 'link',
            feature: RawFeature.ADMIN_CONFIG,
          },
        ],
      },
      {
        title: 'core.menu.settings.title',
        icon: SettingsTwoTone,
        type: 'group',
        features: [
          RawFeature.ASST_ESTATE_BASE,
          RawFeature.ASST_CADASTRAL_LAND_CATEGORY,
          RawFeature.ASST_CATALOGUE_CONFIG,
          RawFeature.PROP_CONTRACT_TYPES,
          RawFeature.COMMON_ACCOUNTINGITEMS,
          RawFeature.COMMON_BILLITEMTYPES,
          RawFeature.COMMON_VATRATES,
          RawFeature.COMMON_INTERESTRATES,
          RawFeature.COMMON_REVALUATIONDATA,
          RawFeature.COMMON_TAX_RATES,
          RawFeature.NRGY_TYPE_BASE,
          RawFeature.FCLT_CONTRACT_TYPES,
          RawFeature.FCLT_CONTRACT_TEMPLATES,
          RawFeature.FCLT_ESTATE_UNIT_GROUP_BASE,
          RawFeature.FCLT_CONFIG,
          RawFeature.FCLT_PENALTY_BASE,
          RawFeature.FCLT_SLA_BASE,
          RawFeature.FCLT_SERVICE_CATEGORY,
        ],
        children: [
          {
            title: 'core.menu.real_estate.title',
            type: 'group',
            features: [
              RawFeature.ASST_ESTATE_BASE,
              RawFeature.ASST_CATALOGUE_CONFIG,
              RawFeature.ASST_CADASTRAL_LAND_CATEGORY,
            ],
            children: [
              {
                title: 'core.menu.settings.real_estate.floors',
                url: '/app/settings/real-estate/floors',
                type: 'link',
                feature: RawFeature.ASST_ESTATE_BASE,
              },
              {
                title: 'core.menu.settings.real_estate.function_areas',
                url: '/app/settings/real-estate/function-areas',
                type: 'link',
                feature: RawFeature.ASST_ESTATE_BASE,
              },
              {
                title: 'core.menu.settings.real_estate.catalogue_types',
                url: '/app/settings/real-estate/catalogue-types',
                type: 'link',
                feature: RawFeature.ASST_CATALOGUE_CONFIG,
              },
              {
                title: 'core.menu.settings.real_estate.catalogue_categories',
                url: '/app/settings/real-estate/catalogue-categories',
                type: 'link',
                feature: RawFeature.ASST_CATALOGUE_CONFIG,
              },
              {
                title: 'core.menu.settings.real_estate.cadastral_land_categories',
                url: '/app/settings/real-estate/cadastral-land-categories',
                type: 'link',
                feature: RawFeature.ASST_CADASTRAL_LAND_CATEGORY,
              },
              {
                title: 'core.menu.settings.real_estate.main_usage_types',
                url: '/app/settings/real-estate/main-usage-types',
                type: 'link',
                feature: RawFeature.ASST_ESTATE_BASE,
              },
              {
                title: 'core.menu.settings.real_estate.usage_types',
                url: '/app/settings/real-estate/usage-types',
                type: 'link',
                feature: RawFeature.ASST_ESTATE_BASE,
              },
            ],
          },
          {
            title: 'core.menu.asset_management.title',
            type: 'group',
            features: [
              RawFeature.PROP_CONTRACT_TYPES,
              RawFeature.COMMON_ACCOUNTINGITEMS,
              RawFeature.COMMON_BILLITEMTYPES,
              RawFeature.COMMON_VATRATES,
              RawFeature.COMMON_INTERESTRATES,
              RawFeature.COMMON_REVALUATIONDATA,
            ],
            children: [
              {
                title: 'core.menu.settings.asset_management.contract_types',
                url: '/app/settings/asset-management/contract-types',
                type: 'link',
                feature: RawFeature.PROP_CONTRACT_TYPES,
              },
              {
                title: 'core.menu.settings.asset_management.accounting_items',
                url: '/app/settings/asset-management/accounting-items',
                type: 'link',
                feature: RawFeature.COMMON_ACCOUNTINGITEMS,
              },
              {
                title: 'core.menu.settings.asset_management.bill_item_types',
                url: '/app/settings/asset-management/bill-item-types',
                type: 'link',
                feature: RawFeature.COMMON_BILLITEMTYPES,
              },
              {
                title: 'core.menu.settings.asset_management.vat_rates',
                url: '/app/settings/asset-management/vat-rates',
                type: 'link',
                feature: RawFeature.COMMON_VATRATES,
              },
              {
                title: 'core.menu.settings.asset_management.interest_rates',
                url: '/app/settings/asset-management/interest-rates',
                type: 'link',
                feature: RawFeature.COMMON_INTERESTRATES,
              },
              {
                title: 'core.menu.settings.asset_management.revaluation_data',
                url: '/app/settings/asset-management/revaluation-data',
                type: 'link',
                feature: RawFeature.COMMON_REVALUATIONDATA,
              },
            ],
          },
          {
            title: 'core.menu.energy_management.title',
            type: 'group',
            features: [RawFeature.NRGY_TYPE_BASE],
            children: [
              {
                title: 'core.menu.settings.energy_management.utility_types',
                url: '/app/settings/energy-management/utility-types',
                type: 'link',
                feature: RawFeature.NRGY_TYPE_BASE,
              },
            ],
          },
          {
            title: 'core.menu.tax_management.title',
            type: 'group',
            features: [RawFeature.COMMON_TAX_RATES],
            children: [
              {
                title: 'core.menu.settings.tax_management.revaluation_coefficients',
                url: '/app/settings/tax-management/revaluation-coefficients',
                type: 'link',
                feature: RawFeature.COMMON_TAX_RATES,
              },
              {
                title: 'core.menu.settings.tax_management.tax_rates',
                url: '/app/settings/tax-management/tax-rates',
                type: 'link',
                feature: RawFeature.COMMON_TAX_RATES,
              },
            ],
          },
          {
            title: 'core.menu.maintenance.title',
            type: 'group',
            features: [
              RawFeature.FCLT_CONTRACT_TYPES,
              RawFeature.FCLT_CONTRACT_TEMPLATES,
              RawFeature.FCLT_ESTATE_UNIT_GROUP_BASE,
              RawFeature.FCLT_CONFIG,
              RawFeature.FCLT_PENALTY_BASE,
              RawFeature.FCLT_SLA_BASE,
              RawFeature.FCLT_SERVICE_CATEGORY,
            ],
            children: [
              {
                title: 'core.menu.settings.maintenance.facility_contract_types',
                url: '/app/settings/maintenance/facility-contract-types',
                type: 'link',
                feature: RawFeature.FCLT_CONTRACT_TYPES,
              },
              {
                title: 'core.menu.settings.maintenance.facility_contract_templates',
                url: '/app/settings/maintenance/facility-contract-templates',
                type: 'link',
                feature: RawFeature.FCLT_CONTRACT_TEMPLATES,
              },
              {
                title: 'core.menu.settings.maintenance.estate_unit_groups',
                url: '/app/settings/maintenance/estate-unit-groups',
                type: 'link',
                feature: RawFeature.FCLT_ESTATE_UNIT_GROUP_BASE,
              },
              {
                title: 'core.menu.settings.maintenance.slas',
                url: '/app/settings/maintenance/slas',
                type: 'link',
                feature: RawFeature.FCLT_SLA_BASE,
              },
              {
                title: 'core.menu.settings.maintenance.penalties',
                url: '/app/settings/maintenance/penalties',
                type: 'link',
                feature: RawFeature.FCLT_PENALTY_BASE,
              },
              {
                title: 'core.menu.settings.maintenance.calendars',
                url: '/app/settings/maintenance/calendars',
                type: 'link',
                feature: RawFeature.FCLT_CONFIG,
              },
              {
                title: 'core.menu.settings.maintenance.ticket_checklist_templates',
                url: '/app/settings/maintenance/ticket-checklist-templates',
                type: 'link',
                feature: RawFeature.FCLT_CONFIG,
              },
              {
                title: 'core.menu.settings.maintenance.intervention_types',
                url: '/app/settings/maintenance/intervention-types',
                type: 'link',
                feature: RawFeature.FCLT_CONFIG,
              },
              {
                title: 'core.menu.settings.maintenance.crafts',
                url: '/app/settings/maintenance/crafts',
                type: 'link',
                feature: RawFeature.FCLT_CONFIG,
              },
              {
                title: 'core.menu.settings.maintenance.qualification_levels',
                url: '/app/settings/maintenance/qualification-levels',
                type: 'link',
                feature: RawFeature.FCLT_CONFIG,
              },
              {
                title: 'core.menu.settings.maintenance.ticket_types',
                url: '/app/settings/maintenance/ticket-types',
                type: 'link',
                feature: RawFeature.FCLT_CONFIG,
              },
              {
                title: 'core.menu.settings.maintenance.price_list_measurement_units',
                url: '/app/settings/maintenance/price-list-measurement-units',
                type: 'link',
                feature: RawFeature.FCLT_CONFIG,
              },
              {
                title: 'core.menu.settings.maintenance.service_categories',
                url: '/app/settings/maintenance/service-categories',
                type: 'link',
                feature: RawFeature.FCLT_SERVICE_CATEGORY,
              },
            ],
          },
        ],
      },
    ],
  },
];
