namespace RealGimm.Plugin.Import.Prop.Models;

public class ContractDTO
{
  public string Id { get; set; } = default!;
  public string? ManagementSubjectId { get; set; }
  public string? UsageTypeId { get; set; }
  public string? ContractTypeId { get; set; }
  public string? EstateId { get; set; }
  public string? InternalCode { get; set; }
  public string? Type { get; set; } //FlagContrattoEnum: A, P, S, Z, T
  public string? OldContractReference { get; set; }
  public DateTime? SigningDate { get; set; }
  public DateTime? StartDate { get; set; }
  public DateTime? EffectivenessDate { get; set; }
  public bool IsSuspended { get; set; }
  public bool IsSolarAligned { get; set; }
  public int? DurationMonths1 { get; set; }
  public int? DurationMonths2 { get; set; }
  public DateTime? ExpirationDate1 { get; set; }
  public DateTime? ExpirationDate2 { get; set; }
  public int? NoticeMonths { get; set; }
  public DateTime? NoticeStartDate { get; set; }
  public DateTime? NoticeEndDate { get; set; }
  public DateTime? BillingStartDate { get; set; }
  public int? CancellationMonths { get; set; }
  public DateTime? CancellationDate { get; set; }
  public DateTime? ReturnDate { get; set; }
  public decimal? AnnualFee { get; set; }
  public decimal? InitialFee { get; set; }
  public string? ReleaseTypeId { get; set; }
  public string? BillingPeriodMonths { get; set; }
  public string? VatTypeId { get; set; }
  public DateTime? InvoiceCompetenceDate { get; set; }
  public bool IsPostponed { get; set; }
  public bool IsNoTitleOccupancy { get; set; }
  public bool IsStampDuty { get; set; }
  public bool IsToBeInvoiced { get; set; }
  public bool IsRecoveryOldAmounts { get; set; }
  public string? BillingItemId { get; set; }
  public int? ValueDateDay { get; set; }
  public bool IsRevaluationEnabled { get; set; }
  public bool IsRevaluationAbsolute { get; set; }
  public bool IsPrintLetter { get; set; }
  public int? RevaluationApplicationMonths { get; set; }
  public int? RevaluationPeriodMonths { get; set; }
  public DateTime? RevaluationStartDate { get; set; }
  public DateTime? RevaluationEndDate { get; set; }
  public decimal? RevaluationFactor { get; set; }
  public bool IsRevaluationCalculated { get; set; }
  public string? BaseAmountFeeReferenceId { get; set; }
  public decimal? BaseAmountFee { get; set; }
  public DateTime? NextRevaluationDate { get; set; }
  public bool IsRegistrationTax { get; set; }
  public bool IsRLI { get; set; }
  public string? RLISeries { get; set; }
  public string? RLISub { get; set; }
  public string? RLINumber { get; set; }
  public DateTime? FirstRegistrationDate { get; set; }
  public string? RLICityId { get; set; }
  public string? RLIContractIdentificationCode { get; set; }
  public string? RliContractTypeForeignKey { get; set; }
  public int? RLILastRegistrationYear { get; set; }
  public DateTime? RLIRegistrationPaymentDate { get; set; }
  public string? RLIRegistrationOfficeCode { get; set; }
  public decimal? RLIRentFactor { get; set; }
  public int? RLIYearsToApply { get; set; }
  public bool IsOurChargeRegistration { get; set; }
  public decimal? RLITenantChargeFactor { get; set; }
  public string? RLIPaymentType { get; set; }
  public bool IsRLITelematic { get; set; }
  public DateTime? RLILastTelePaymentDate { get; set; }
  public DateTime? FirstTeleRegistrationDate { get; set; }
  public int? ContractPages { get; set; }
  public int? CopiesNumber { get; set; }
  public decimal? StampDutyAmount { get; set; }
  public decimal? StampDutyTenantChargeFactor { get; set; }
  public bool IsVatRli { get; set; }
  public bool IsExemptionFlag { get; set; }
  public bool IsDeposit { get; set; }
  public DateTime? DepositReturnDate { get; set; }
  public string? DepositNotes { get; set; }
  public DateTime? InterestStartDate { get; set; }
  public DateTime? InterestEndDate { get; set; }
  public decimal? InterestRate { get; set; }
  public bool IsLegalInterest { get; set; }
  public decimal? TotalDepositInterests { get; set; }
  public string? LiquidationType { get; set; }
  public DateTime? InterestDate { get; set; }
  public DateTime? LiquidationDate { get; set; }
  public bool IsPenalRate { get; set; }
  public decimal? LegalRate { get; set; }
  public decimal? FreeRate { get; set; }
  public decimal? UsRate { get; set; }
  public string? LatePaymentType { get; set; }
  public bool IsReturnDelayPenalty { get; set; }
  public decimal? ReturnDelayRate { get; set; }
  public decimal? UnitPrice { get; set; }
  public string? UnitPriceCoefficientType { get; set; }
  public string? Notes { get; set; }
  public DateTime? UpdateDate { get; set; }
  public bool IsTerminated { get; set; }
  public bool IsInstrumental { get; set; }
  public bool IsRegistrationTaxBers { get; set; }
  public DateTime? AltNextRevaluationDate { get; set; }
  public bool IsAltIstatArrear { get; set; }
  public string? SpendingResolution { get; set; }
  public DateTime? SpendingResolutionDate { get; set; }
  public string? FeeResolution { get; set; }
  public DateTime? FeeResolutionDate { get; set; }
  public string? SortingTypeId { get; set; }
  public string? InvoiceNote { get; set; }
  public bool IsInvoiceNote { get; set; }
  public bool IsManualF23 { get; set; }
  public decimal? AssignmentConsideration { get; set; }
  public string? LeasingObjectTypeId { get; set; }
  public DateTime? FirstExpirationDate { get; set; }
  public string? CancellationBy { get; set; }
  public bool IsNonRenewable { get; set; }
  public string? SettlementTermId { get; set; }
  public string? BranchToBeCredited { get; set; }
  public string? LeasingCode { get; set; }
  public string? ExpenseCode { get; set; }
  public string? GroupingCode { get; set; }
  public string? CounterpartGroupCode { get; set; }
  public bool IsSplitPayment { get; set; }
  public bool IsEnableSplitPayment { get; set; }  //Looks unused
  public bool IsVoluntaryPenaltyClause { get; set; }
  public string? VatRateId { get; set; }
}
